AtithiApp/urls.py
from django.urls import path
from . import views

app_name = 'AtithiApp'
urlpatterns = [
    path('login/',views.userLogin, name='login'),
    path('dashboard/',views.DashboardPage.as_view(), name='dashboard'),
    path('departures/',views.Departure.as_view(), name='departures'),
    path('paststay/', views.PastStay.as_view(), name='paststay'),
    path('search/', views.Search.as_view(), name='search'),
    path('selectDates/', views.SelectDates.as_view(), name='selectDates'),
    path('inhouse/',views.InHouse.as_view(), name='inhouse'),
    path('admin/',views.Admin.as_view(), name='admin'),
    path('logout/',views.logoutRequest, name='logout'),
    path('checkin/',views.checkIn,name='checkin'),
]

venhouston/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include,path
from AtithiApp.views import userLogin

urlpatterns = [
    path('', userLogin, name="home"),
    path('admin/', admin.site.urls),
    path('AtithiApp/', include('AtithiApp.urls')),
]

AtithiApp/models.py
from django.db import models
from datetime import datetime

# Create your models here.
class Guest(models.Model):
    driverLicense = models.CharField(max_length=255)
    firstName = models.CharField(max_length=50)
    lastName = models.CharField(max_length=50)
    gender = models.CharField(max_length=1)
    address1 = models.CharField(max_length=50)
    phoneNumber = models.CharField(max_length=15)
    city = models.CharField(max_length=50)
    state = models.CharField(max_length=50)
    zipcode = models.IntegerField()
    dob = models.DateField()
    checkin = models.DateField(default=datetime.today().strftime('%Y-%m-%d'))
    checkout = models.DateField(default=datetime.today().strftime('%Y-%m-%d'))
    adults = models.IntegerField(null=True)
    children = models.IntegerField(null=True)
    paymentAmount = models.IntegerField(null=True)
    petFee = models.IntegerField(default=0)
    roomNumber = models.IntegerField(null=True)

AtithiApp/forms.py
from . models import *
from django.contrib.auth.forms import *
from django.contrib.auth.models import User


class DateInput(forms.DateInput):
    input_type = 'date'


User = get_user_model()


class UserLogin(forms.Form):
    username = forms.CharField(widget=forms.TextInput(attrs={'class':'form-control'}))
    password = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control'}))

    def clean(self, *args, **kwargs):
        username = self.cleaned_data.get('username')
        password = self.cleaned_data.get('password')

        if username and password:
            user = authenticate(username=username, password=password)

            if not user:
                raise forms.ValidationError('This user does not exist')
            if not user.check_password(password):
                raise forms.ValidationError('Incorrect Password')
            if not user.is_active:
                raise forms.ValidationError('This User is not active')

        log = super(UserLogin, self).clean(*args, **kwargs)
        return log


class CheckInForm(forms.Form):
    def __init__(self,*args,**kwargs):
        self.request = kwargs.pop('request',None)
        super(CheckInForm,self).__init__(*args,**kwargs)

        CHOICES = (
            ('','Select Gender'),
            ('M', 'Male'),
            ('F', 'Female'),
        )

        self.fields['firstName'] = forms.CharField(required=True,
            widget=forms.TextInput(attrs={'class':'form-detail','placeholder':'First Name','id':'firstName'}))

        self.fields['lastName'] = forms.CharField(required=True,
            widget=forms.TextInput(attrs={'class':'form-detail','placeholder':'Last Name','id':'lastName'}))

        self.fields['gender'] = forms.ChoiceField(required=True,choices=CHOICES,
            widget=forms.Select(attrs={'class': 'form-detail', 'placeholder': 'Gender', 'id': 'gender'}))

        self.fields['dob'] = forms.DateField(required=True,
            widget=DateInput(attrs={'class': 'form-detail', 'placeholder': 'mm/dd/yyyy', 'id': 'dob'}))

        self.fields['address1'] = forms.CharField(required=True,
            widget=forms.TextInput(attrs={'class':'form-detail','placeholder':'Street Address 1','id':'address1'}))

        self.fields['city'] = forms.CharField(required=True,
            widget=forms.TextInput(attrs={'class':'form-detail','placeholder':'City','id':'city'}))

        self.fields['state'] = forms.CharField(required=True,
            widget=forms.TextInput(attrs={'class':'form-detail','placeholder':'State','id':'state'}))

        self.fields['zipcode'] = forms.CharField(required=True,
            widget=forms.TextInput(attrs={'class': 'form-detail', 'placeholder': 'Zip Code', 'id': 'zipcode'}))

        self.fields['phoneNumber'] = forms.CharField(required=True,
            widget=forms.TextInput(attrs={'class':'form-detail','placeholder':'Phone Number','id':'phoneNumber'}))

        self.fields['driverLicense'] = forms.CharField(required=True,
            widget=forms.TextInput(attrs={'class':'form-detail','placeholder':'Driver License','id':'driverLicense'}))

        self.fields['checkin'] = forms.DateField(required=True,
            widget=DateInput(attrs={'class': 'form-detail', 'placeholder': 'mm/dd/yyyy', 'id': 'checkin'}))

        self.fields['checkout'] = forms.DateField(required=True,
            widget=DateInput(attrs={'class': 'form-detail', 'placeholder': 'mm/dd/yyyy', 'id': 'checkout'}))

        self.fields['adults'] = forms.IntegerField(
            widget=forms.TextInput(attrs={'class': 'form-detail', 'placeholder': 'No of Adults', 'id': 'adults'}))

        self.fields['children'] = forms.IntegerField(
            widget=forms.TextInput(attrs={'class': 'form-detail', 'placeholder': 'No of Children', 'id': 'children'}))

        self.fields['paymentAmount'] = forms.IntegerField(
            widget=forms.TextInput(attrs={'class': 'form-detail', 'placeholder': 'Payment Amount (Incl. Taxes)', 'id': 'paymentAmount'}))

        self.fields['petFee'] = forms.IntegerField(
            widget=forms.TextInput(attrs={'class': 'form-detail', 'placeholder': 'Pet Fee', 'id': 'petFee'}))

        self.fields['roomNumber'] = forms.IntegerField(
            widget=forms.TextInput(attrs={'class': 'form-detail', 'placeholder': 'Room Number', 'id': 'roomNumber'}))

    class Meta:
        guest = Guest
        widgets = {'dob': DateInput(), 'checkin': DateInput(), 'checkout': DateInput(),
                   }
        fields = [
            'driverLicense', 'firstName', 'lastName', 'gender',
            'address1', 'city', 'state', 'zipcode',
            'dob', 'phoneNumber',
            'checkin','checkout','adults', 'children',
            'paymentAmount','roomNumber','petFee',
        ]

    def save(self, commit=True):
        guest = Guest()
        guest.driverLicense = self.cleaned_data['driverLicense']
        guest.firstName = self.cleaned_data['firstName']
        guest.lastName = self.cleaned_data['lastName']
        guest.gender = self.cleaned_data['gender']
        guest.address1 = self.cleaned_data['address1']
        guest.city = self.cleaned_data['city']
        guest.state = self.cleaned_data['state']
        guest.zipcode = self.cleaned_data['zipcode']
        guest.dob = self.cleaned_data['dob']
        guest.phoneNumber = self.cleaned_data['phoneNumber']
        guest.checkin = self.cleaned_data['checkin']
        guest.checkout = self.cleaned_data['checkout']
        guest.adults = self.cleaned_data['adults']
        guest.children = self.cleaned_data['children']
        guest.paymentAmount = self.cleaned_data['paymentAmount']
        guest.petFee = self.cleaned_data['petFee']
        guest.roomNumber = self.cleaned_data['roomNumber']

        if commit is True:
            guest.save()

        return guest

AtithiApp/views.py
from django.views.generic import TemplateView
from . forms import *
from django.shortcuts import redirect, render
from django.contrib.auth import login, authenticate, logout
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator


def userLogin(request):
    next = request.GET.get('next')
    form = UserLogin(request.POST or None)

    if request.user.is_authenticated:
        return redirect('AtithiApp:dashboard')

    if form.is_valid():
        username = form.cleaned_data.get('username')
        password = form.cleaned_data.get('password')
        user = authenticate(username = username, password = password)
        login(request, user)
        if next:
            return redirect(next)
        return redirect('/AtithiApp/dashboard')

    context = {
        'form': form,
    }
    return render(request, "AtithiApp/login.html",context)


def logoutRequest(request):
    logout(request)
    return redirect("AtithiApp:login")


@method_decorator(login_required, name='dispatch')
class DashboardPage(TemplateView):
    template_name = "AtithiApp/dashboard.html"

    def get(self, request):
        currentUser = request.user

        args = {'currentUser':currentUser}
        return render(request,self.template_name,args)

    def post(self,request):
        currentUser = request.user
        print(request.POST)
        args = {'currentUser': currentUser}
        return render(request, self.template_name, args)


@login_required()
def checkIn(request):
    form = CheckInForm(request=request)
    if request.method == 'POST':
        form = CheckInForm(request.POST,request=request)
        print(request.POST)
        if form.is_valid():
            form.save()
            return redirect('AtithiApp:dashboard')
        else:
            print(form.errors)
    context = {
        "form": form,
        "currentUser": request.user,
    }
    return render(request, "AtithiApp/checkin.html", context)


@method_decorator(login_required, name='dispatch')
class InHouse(TemplateView):
    template_name = "AtithiApp/inhouse.html"

    def get(self, request):
        guestList = Guest.objects.all()
        currentUser = request.user

        args = {
            'currentUser': currentUser,
            'guestList': guestList,
        }
        return render(request,self.template_name,args)


@method_decorator(login_required, name='dispatch')
class Admin(TemplateView):
    template_name = "AtithiApp/admin.html"

    def get(self, request):
        currentUser = request.user

        args = {'currentUser':currentUser}
        return render(request,self.template_name,args)

    def post(self,request):
        currentUser = request.user
        print(request.POST)
        args = {'currentUser': currentUser}
        return render(request, self.template_name, args)


@method_decorator(login_required, name='dispatch')
class Departure(TemplateView):
    template_name = "AtithiApp/departures.html"

    def get(self, request):
        currentUser = request.user

        args = {'currentUser':currentUser}
        return render(request,self.template_name,args)

    def post(self,request):
        currentUser = request.user
        print(request.POST)
        args = {'currentUser': currentUser}
        return render(request, self.template_name, args)


@method_decorator(login_required, name='dispatch')
class PastStay(TemplateView):
    template_name = "AtithiApp/paststay.html"

    def get(self, request):
        currentUser = request.user

        args = {'currentUser':currentUser}
        return render(request,self.template_name,args)


@method_decorator(login_required, name='dispatch')
class Search(TemplateView):
    template_name = "AtithiApp/search.html"

    def get(self, request):
        currentUser = request.user
        dl = request.GET['dl']

        guest = Guest.objects.filter(driverLicense__icontains=dl).first()

        args = {
            'currentUser':currentUser,
            'guest': guest,
        }
        return render(request,self.template_name,args)

    def post(self,request):
        currentUser = request.user
        print(request.POST)
        args = {'currentUser': currentUser}
        return render(request, self.template_name, args)


@method_decorator(login_required, name='dispatch')
class SelectDates(TemplateView):
    template_name = "AtithiApp/selectDates.html"

    def get(self, request):
        current_user = request.user
        dl = request.GET['dl']
        personal_form = CheckInForm(request=request)
        guest = Guest.objects.filter(driverLicense__icontains=dl).first()

        args = {
            'personalForm': personal_form,
            'currentUser': current_user,
            'guest': guest,
        }
        return render(request,self.template_name,args)

    def post(self, request):
        current_user = request.user
        print(request.POST)
        args = {'currentUser': current_user}
        return render(request, self.template_name, args)

AtithiApp/templates/AtithiApp/admin.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>Atithi Management System</title>
    <link rel="stylesheet" href="{% static 'AtithiApp/css/splash.css' %}">
    <script src="https://kit.fontawesome.com/57d8462694.js" crossorigin="anonymous"></script>
</head>
<body>
<div class="wrapper">
    <div class="sidebar">
        <h2 onclick="home()"> {{ currentUser.first_name }}</h2>
        <ul class="mainmenu">

            <li><a href="{% url 'AtithiApp:dashboard' %}"> <i class="fas fa-chart-line"></i> Dashboard </a>
                <ul class="submenu">

                </ul>
            </li>

            <li><a href="{% url 'AtithiApp:departures' %}"> <i class="fas fa-plane-departure"></i> Departures </a>
                <ul class="submenu">

                </ul>
            </li>

            <li><a href="{% url 'AtithiApp:inhouse' %}"> <i class="fas fa-home"></i> In House </a>
                <ul class="submenu">

                </ul>
            </li>

            <li><a href="{% url 'AtithiApp:paststay' %}"> <i class="fas fa-plane-arrival"></i> Arrivals </a>
                <ul class="submenu">

                </ul>
            </li>

            {% if currentUser.is_superuser %}
                <li><a href="#"> <i class="fas fa-user-cog"></i> Admin </a>
                    <ul class="submenu">

                    </ul>
                </li>
            {% endif %}

            {% if user.is_authenticated %}
                <li><a href="{% url 'AtithiApp:logout' %}"> <i class="fas fa-door-open"></i> Logout </a> </li>
            {% endif %}
        </ul>
    </div>
</div>
<script src="{% static 'AtithiApp/js/viewList.js' %}"></script>
</body>
</html>

AtithiApp/templates/AtithiApp/arrivals.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>Atithi Management System</title>
    <link rel="stylesheet" href="{% static 'AtithiApp/css/splash.css' %}">
    <script src="https://kit.fontawesome.com/57d8462694.js" crossorigin="anonymous"></script>
</head>
<body>
<div class="wrapper">
    <div class="sidebar">
        <h2 onclick="home()"> {{ currentUser.first_name }}</h2>
        <ul class="mainmenu">

            <li><a href="{% url 'AtithiApp:dashboard' %}"> <i class="fas fa-chart-line"></i> Dashboard </a>
                <ul class="submenu">

                </ul>
            </li>

            <li><a href="{% url 'AtithiApp:departures' %}"> <i class="fas fa-plane-departure"></i> Departures </a>
                <ul class="submenu">

                </ul>
            </li>

            <li><a href="{% url 'AtithiApp:inhouse' %}"> <i class="fas fa-home"></i> In House </a>
                <ul class="submenu">

                </ul>
            </li>

            <li><a href="{% url 'AtithiApp:paststay' %}"> <i class="fas fa-plane-arrival"></i> Arrivals </a>
                <ul class="submenu">

                </ul>
            </li>

            {% if currentUser.is_superuser %}
                <li><a href="#"> <i class="fas fa-user-cog"></i> Admin </a>
                    <ul class="submenu">

                    </ul>
                </li>
            {% endif %}

            {% if user.is_authenticated %}
                <li><a href="{% url 'AtithiApp:logout' %}"> <i class="fas fa-door-open"></i> Logout </a> </li>
            {% endif %}
        </ul>
    </div>
</div>
<script src="{% static 'AtithiApp/js/viewList.js' %}"></script>
</body>
</html>

AtithiApp/templates/AtithiApp/checkin.html
{% load static %}
<!DOCTYPE html>
<html>
<head><link rel="stylesheet" href="{% static 'AtithiApp/css/splash.css' %}">
    <link rel="stylesheet" href="{% static 'AtithiApp/css/register.css' %}">
    <link rel="stylesheet" href="{% static 'AtithiApp/css/checkin.css' %}">
    <script src="https://kit.fontawesome.com/57d8462694.js" crossorigin="anonymous"></script>
</head>
<body>
<div class="wrapper">
    <div class="sidebar">
        <h2 onclick="home()"> {{ currentUser.first_name }} </h2>
        <ul class="mainmenu">

            <li><a href="{% url 'AtithiApp:dashboard' %}"> <i class="fas fa-chart-line"></i> Dashboard </a>
                <ul class="submenu">

                </ul>
            </li>

            <li><a href="{% url 'AtithiApp:departures' %}"> <i class="fas fa-plane-departure"></i> Departures </a>
                <ul class="submenu">

                </ul>
            </li>

            <li><a href="{% url 'AtithiApp:inhouse' %}"> <i class="fas fa-home"></i> In House </a>
                <ul class="submenu">

                </ul>
            </li>

            <li><a href="{% url 'AtithiApp:paststay' %}"> <i class="fas fa-plane-arrival"></i> Arrivals </a>
                <ul class="submenu">

                </ul>
            </li>

            {% if currentUser.is_superuser %}
                <li><a href="#"> <i class="fas fa-user-cog"></i> Admin </a>
                    <ul class="submenu">

                    </ul>
                </li>
            {% endif %}

            {% if user.is_authenticated %}
                <li><a href="{% url 'AtithiApp:logout' %}"> <i class="fas fa-door-open"></i> Logout </a> </li>
            {% endif %}
        </ul>
    </div>

    <div class="page-content">
        <div class="form-v10-content">

            <form class="form-detail" action="#" method="post" id="regform"> {% csrf_token %}
                <div class="form-right ">


                    <div class="tab">
                        <h1 style="margin-top: 40px">Check In</h1>
                        <h2>Personal Information:</h2>
                        <div class="form-group">
                            <div class="form-row form-row-1"> {{ form.firstName }} </div>
                            <div class="form-row form-row-2"> {{ form.lastName }} </div>
                        </div>

                        <div class="form-row"> {{ form.gender }} </div>
                        <div class="form-row"> {{ form.address1 }} </div>
                        <div class="form-row"> {{ form.city }} </div>
                        <div class="form-group">
                            <div class="form-row form-row-1"> {{ form.state }} </div>
                            <div class="form-row form-row-2"> {{ form.zipcode }} </div>
                        </div>
                        <div class="form-group">
                            <div class="form-row form-row-1"> {{ form.driverLicense }} </div>
                            <div class="form-row form-row-2"> {{ form.dob }} </div>
                        </div>
                        <div class="form-row"> {{ form.phoneNumber }} </div>
                    </div>

                    <div class="tab">
                        <h1 style="margin-top: 40px">Check In</h1>
                        <h2>Stay Information:</h2>
                        <div class="form-row"> {{ form.checkin }} </div>
                        <div class="form-row"> {{ form.checkout }} </div>
                        <div class="form-row"> {{ form.adults }} </div>
                        <div class="form-row"> {{ form.children }} </div>
                    </div>

                    <div class="tab">
                        <h1 style="margin-top: 40px">Check In</h1>
                        <h2>Payment Information:</h2>
                        <div class="form-row"> {{ form.paymentAmount }} </div>
                        <div class="form-row"> {{ form.petFee }} </div>
                        <div class="form-row"> {{ form.roomNumber }} </div>
                    </div>

                    <div style="text-align: center; padding: 15px;">
                        <button type="button" id="prevBtn" onclick="nextPrev(-1)">Previous</button>
                        <button type="button" id="nextBtn" onclick="nextPrev(1)">Next</button>
                    </div>

                    <div style="text-align:center;margin:20px 40px 40px 40px; ">
                        <span class="step"></span>
                        <span class="step"></span>
                        <span class="step"></span>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
<script src="{% static 'AtithiApp/js/checkin.js' %}"></script>
</body>
</html>

AtithiApp/templates/AtithiApp/dashboard.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>Atithi Management System</title>
    <link rel="stylesheet" href="{% static 'AtithiApp/css/splash.css' %}">
    <link rel="stylesheet" href="{% static 'AtithiApp/css/dashboard.css' %}">
    <script src="https://kit.fontawesome.com/57d8462694.js" crossorigin="anonymous"></script>
</head>
<body>
<div class="wrapper">
    <div class="sidebar">
        <h2 onclick="home()"> {{ currentUser.first_name }}</h2>
        <ul class="mainmenu">

            <li><a href="{% url 'AtithiApp:dashboard' %}"> <i class="fas fa-chart-line"></i> Dashboard </a>
                <ul class="submenu">

                </ul>
            </li>

            <li><a href="{% url 'AtithiApp:departures' %}"> <i class="fas fa-plane-departure"></i> Departures </a>
                <ul class="submenu">

                </ul>
            </li>

            <li><a href="{% url 'AtithiApp:inhouse' %}"> <i class="fas fa-home"></i> In House </a>
                <ul class="submenu">

                </ul>
            </li>

            <li><a href="{% url 'AtithiApp:paststay' %}"> <i class="fas fa-plane-arrival"></i> Arrivals </a>
                <ul class="submenu">

                </ul>
            </li>

            {% if currentUser.is_superuser %}
                <li><a href="#"> <i class="fas fa-user-cog"></i> Admin </a>
                    <ul class="submenu">

                    </ul>
                </li>
            {% endif %}

            {% if user.is_authenticated %}
                <li><a href="{% url 'AtithiApp:logout' %}"> <i class="fas fa-door-open"></i> Logout </a> </li>
            {% endif %}
        </ul>
    </div>
</div>
<script src="{% static 'AtithiApp/js/viewList.js' %}"></script>
</body>
</html>

AtithiApp/templates/AtithiApp/departures.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>Atithi Management System</title>
    <link rel="stylesheet" href="{% static 'AtithiApp/css/splash.css' %}">
    <script src="https://kit.fontawesome.com/57d8462694.js" crossorigin="anonymous"></script>
</head>
<body>
<div class="wrapper">
    <div class="sidebar">
        <h2 onclick="home()"> {{ currentUser.first_name }}</h2>
        <ul class="mainmenu">

            <li><a href="{% url 'AtithiApp:dashboard' %}"> <i class="fas fa-chart-line"></i> Dashboard </a>
                <ul class="submenu">

                </ul>
            </li>

            <li><a href="{% url 'AtithiApp:departures' %}"> <i class="fas fa-plane-departure"></i> Departures </a>
                <ul class="submenu">

                </ul>
            </li>

            <li><a href="{% url 'AtithiApp:inhouse' %}"> <i class="fas fa-home"></i> In House </a>
                <ul class="submenu">

                </ul>
            </li>

            <li><a href="{% url 'AtithiApp:paststay' %}"> <i class="fas fa-plane-arrival"></i> Arrivals </a>
                <ul class="submenu">

                </ul>
            </li>

            {% if currentUser.is_superuser %}
                <li><a href="#"> <i class="fas fa-user-cog"></i> Admin </a>
                    <ul class="submenu">

                    </ul>
                </li>
            {% endif %}

            {% if user.is_authenticated %}
                <li><a href="{% url 'AtithiApp:logout' %}"> <i class="fas fa-door-open"></i> Logout </a> </li>
            {% endif %}
        </ul>

    </div>
    <div class="main_content">
        <div class="header"> <h3> Atithi Management System </h3> </div>
        <div class="info">
            <div>
                <p>
                    Welcome to the Atithi Management System. <br>
                    We appreciate your business with us.
                </p>
            </div>
        </div>
    </div>
</div>
<script src="{% static 'AtithiApp/js/viewList.js' %}"></script>
</body>
</html>

AtithiApp/templates/AtithiApp/login.html
{% load static %}
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <title>Atithi Login</title>
        <link rel="stylesheet" href="{% static 'AtithiApp/css/login.css' %}">
    </head>
    <body>
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <body>
            <h2>Atithi Login</h2>
            <main>
                <form action="" method="post">
                    {% csrf_token %}
                    {{ form }}
                    <input type="submit" value="Log in">
                </form>
            </main>
        </body>
    </body>
</html>

AtithiApp/templates/AtithiApp/paststay.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>Atithi Management System</title>
    <link rel="stylesheet" href="{% static 'AtithiApp/css/splash.css' %}">
    <link rel="stylesheet" href="{% static 'AtithiApp/css/paststay.css' %}">
    <script src="https://kit.fontawesome.com/57d8462694.js" crossorigin="anonymous"></script>
</head>
<body>
<div class="wrapper">
    <div class="sidebar">
        <h2 onclick="home()"> {{ currentUser.first_name }}</h2>
        <ul class="mainmenu">

            <li><a href="{% url 'AtithiApp:dashboard' %}"> <i class="fas fa-chart-line"></i> Dashboard </a>
                <ul class="submenu">

                </ul>
            </li>

            <li><a href="{% url 'AtithiApp:departures' %}"> <i class="fas fa-plane-departure"></i> Departures </a>
                <ul class="submenu">

                </ul>
            </li>

            <li><a href="{% url 'AtithiApp:inhouse' %}"> <i class="fas fa-home"></i> In House </a>
                <ul class="submenu">

                </ul>
            </li>

            <li><a href="{% url 'AtithiApp:paststay' %}"> <i class="fas fa-plane-arrival"></i> Arrivals </a>
                <ul class="submenu">

                </ul>
            </li>

            {% if currentUser.is_superuser %}
                <li><a href="#"> <i class="fas fa-user-cog"></i> Admin </a>
                    <ul class="submenu">

                    </ul>
                </li>
            {% endif %}

            {% if user.is_authenticated %}
                <li><a href="{% url 'AtithiApp:logout' %}"> <i class="fas fa-door-open"></i> Logout </a> </li>
            {% endif %}
        </ul>

    </div>
    <div class="main_content">
        <p class="fontColor">Have you stayed with us before ?</p>
        <div class="flex-container">
            <div> <a class="button" onclick="existingGuest()"> Yes </a> </div>
            <div> <a href={% url 'AtithiApp:checkin' %} class="button"> No </a> </div>
        </div>
    </div>
    <div id="yesGuest">
        {#        <form class="#" method="GET" action="{% url 'AtithiApp:search' %}">#}
        <form class="#" method="GET" action="{% url 'AtithiApp:selectDates' %}">
            <input class="existingDL" type="text" name="dl" placeholder="Enter Driver License" />
            <div class="existingGuestForm">
                <input type="submit" class="button" value="Submit" />
                <a href="#" class="button" onclick="hideGuest()" > Cancel </a>
            </div>
        </form>
    </div>

</div>
<script src="{% static 'AtithiApp/js/script.js' %}"></script>
</body>
</html>